// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.8.0
// source: list_documents.proto

package lists

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "vectara.com/public/proto/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to list documents in a corpus.
type ListDocumentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The Corpus ID.
	CorpusId uint32 `protobuf:"varint,5,opt,name=corpus_id,json=corpusId,proto3" json:"corpus_id,omitempty"`
	// Maximum number of results to be returned by the server.
	// Max is 1000.
	// If the value is larger than 1000, it will be capped to 1000.
	NumResults uint32 `protobuf:"varint,10,opt,name=num_results,json=numResults,proto3" json:"num_results,omitempty"`
	// Key of the specific page of the list results to return.
	// Null/empty value means the very first page of the results is requested.
	PageKey []byte `protobuf:"bytes,15,opt,name=page_key,json=pageKey,proto3" json:"page_key,omitempty"`
	// Filter on document metadata. If empty, no filtering is done.
	// Otherwise, only documents that match all of the specified metadata
	// will be returned. The syntax is the same as for QueryRequest.metadata.
	MetadataFilter string `protobuf:"bytes,20,opt,name=metadata_filter,json=metadataFilter,proto3" json:"metadata_filter,omitempty"`
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_list_documents_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_list_documents_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_list_documents_proto_rawDescGZIP(), []int{0}
}

func (x *ListDocumentsRequest) GetCorpusId() uint32 {
	if x != nil {
		return x.CorpusId
	}
	return 0
}

func (x *ListDocumentsRequest) GetNumResults() uint32 {
	if x != nil {
		return x.NumResults
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageKey() []byte {
	if x != nil {
		return x.PageKey
	}
	return nil
}

func (x *ListDocumentsRequest) GetMetadataFilter() string {
	if x != nil {
		return x.MetadataFilter
	}
	return ""
}

// Response of listing documents in a corpus.
type ListDocumentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of documents.
	Document []*ListDocumentsResponse_DocumentInfo `protobuf:"bytes,1,rep,name=document,proto3" json:"document,omitempty"`
	// Represents the pagination key to retrieve the next page of results.
	// If the value is "", it means no further results for the request.
	// To retrieve the next page of results, client shall pass the value of next_page_key in the subsequent
	// ListDocumentsRequest method call (in the request message's page_key field).
	NextPageKey []byte `protobuf:"bytes,5,opt,name=next_page_key,json=nextPageKey,proto3" json:"next_page_key,omitempty"`
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_list_documents_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_list_documents_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_list_documents_proto_rawDescGZIP(), []int{1}
}

func (x *ListDocumentsResponse) GetDocument() []*ListDocumentsResponse_DocumentInfo {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *ListDocumentsResponse) GetNextPageKey() []byte {
	if x != nil {
		return x.NextPageKey
	}
	return nil
}

// Document information format of each document in the list.
type ListDocumentsResponse_DocumentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The document ID that was used when indexing the document.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Document metadata.
	Metadata []*common.Attribute `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *ListDocumentsResponse_DocumentInfo) Reset() {
	*x = ListDocumentsResponse_DocumentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_list_documents_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDocumentsResponse_DocumentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse_DocumentInfo) ProtoMessage() {}

func (x *ListDocumentsResponse_DocumentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_list_documents_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse_DocumentInfo.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse_DocumentInfo) Descriptor() ([]byte, []int) {
	return file_list_documents_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListDocumentsResponse_DocumentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListDocumentsResponse_DocumentInfo) GetMetadata() []*common.Attribute {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_list_documents_proto protoreflect.FileDescriptor

var file_list_documents_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65, 0x63, 0x74,
	0x61, 0x72, 0x61, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x1a, 0x0f, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x01, 0x0a, 0x14, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x72, 0x70, 0x75, 0x73, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x6f, 0x72, 0x70, 0x75, 0x73, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x0f,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xe2, 0x01, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x51, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x35, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65, 0x63, 0x74, 0x61, 0x72, 0x61, 0x2e,
	0x6c, 0x69, 0x73, 0x74, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x50,
	0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x1a, 0x52, 0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76,
	0x65, 0x63, 0x74, 0x61, 0x72, 0x61, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x42, 0x3f, 0x0a, 0x11, 0x63, 0x6f,
	0x6d, 0x2e, 0x76, 0x65, 0x63, 0x74, 0x61, 0x72, 0x61, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x42,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x1e, 0x76, 0x65, 0x63,
	0x74, 0x61, 0x72, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_list_documents_proto_rawDescOnce sync.Once
	file_list_documents_proto_rawDescData = file_list_documents_proto_rawDesc
)

func file_list_documents_proto_rawDescGZIP() []byte {
	file_list_documents_proto_rawDescOnce.Do(func() {
		file_list_documents_proto_rawDescData = protoimpl.X.CompressGZIP(file_list_documents_proto_rawDescData)
	})
	return file_list_documents_proto_rawDescData
}

var file_list_documents_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_list_documents_proto_goTypes = []interface{}{
	(*ListDocumentsRequest)(nil),               // 0: com.vectara.lists.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),              // 1: com.vectara.lists.ListDocumentsResponse
	(*ListDocumentsResponse_DocumentInfo)(nil), // 2: com.vectara.lists.ListDocumentsResponse.DocumentInfo
	(*common.Attribute)(nil),                   // 3: com.vectara.Attribute
}
var file_list_documents_proto_depIdxs = []int32{
	2, // 0: com.vectara.lists.ListDocumentsResponse.document:type_name -> com.vectara.lists.ListDocumentsResponse.DocumentInfo
	3, // 1: com.vectara.lists.ListDocumentsResponse.DocumentInfo.metadata:type_name -> com.vectara.Attribute
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_list_documents_proto_init() }
func file_list_documents_proto_init() {
	if File_list_documents_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_list_documents_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDocumentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_list_documents_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDocumentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_list_documents_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDocumentsResponse_DocumentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_list_documents_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_list_documents_proto_goTypes,
		DependencyIndexes: file_list_documents_proto_depIdxs,
		MessageInfos:      file_list_documents_proto_msgTypes,
	}.Build()
	File_list_documents_proto = out.File
	file_list_documents_proto_rawDesc = nil
	file_list_documents_proto_goTypes = nil
	file_list_documents_proto_depIdxs = nil
}
