// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.8.0
// source: indexing_core.proto

package indexingcore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	customdim "vectara.com/public/proto/customdim"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Part of a document. A document consists of several such parts.
type CoreDocumentPart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A part of the document. e.g., a sentence.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Context of the part.
	Context string `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	// Metadata about this part of the document. This should be a json string.
	// It is passed through the system, without being used at indexing time. It
	// can be retrieved at query time.
	MetadataJson string `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	// A list of custom dimension values that are included in the generated
	// representation of this part.  These are optional and take on the corpus
	// default custom dimension value if not explicitly provided for the document
	CustomDims []*customdim.CustomDimension `protobuf:"bytes,4,rep,name=custom_dims,json=customDims,proto3" json:"custom_dims,omitempty"`
}

func (x *CoreDocumentPart) Reset() {
	*x = CoreDocumentPart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_indexing_core_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoreDocumentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreDocumentPart) ProtoMessage() {}

func (x *CoreDocumentPart) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_core_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreDocumentPart.ProtoReflect.Descriptor instead.
func (*CoreDocumentPart) Descriptor() ([]byte, []int) {
	return file_indexing_core_proto_rawDescGZIP(), []int{0}
}

func (x *CoreDocumentPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CoreDocumentPart) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *CoreDocumentPart) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *CoreDocumentPart) GetCustomDims() []*customdim.CustomDimension {
	if x != nil {
		return x.CustomDims
	}
	return nil
}

// A document to index.
type CoreDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A document ID to assign to this document.
	DocumentId string `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	// Metadata about the document. This should be a json string. It can be
	// retrieved at query time.
	MetadataJson string `protobuf:"bytes,2,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	// All parts of this document.
	Parts []*CoreDocumentPart `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
	// This field provides a way to specify a blanket context for all parts. If
	// the context in a part is empty, this context will be used.
	DefaultPartContext string `protobuf:"bytes,4,opt,name=default_part_context,json=defaultPartContext,proto3" json:"default_part_context,omitempty"`
	// A list of custom dimension values that are included in the generated
	// representation of all parts.
	CustomDims []*customdim.CustomDimension `protobuf:"bytes,5,rep,name=custom_dims,json=customDims,proto3" json:"custom_dims,omitempty"`
}

func (x *CoreDocument) Reset() {
	*x = CoreDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_indexing_core_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoreDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreDocument) ProtoMessage() {}

func (x *CoreDocument) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_core_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreDocument.ProtoReflect.Descriptor instead.
func (*CoreDocument) Descriptor() ([]byte, []int) {
	return file_indexing_core_proto_rawDescGZIP(), []int{1}
}

func (x *CoreDocument) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CoreDocument) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *CoreDocument) GetParts() []*CoreDocumentPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *CoreDocument) GetDefaultPartContext() string {
	if x != nil {
		return x.DefaultPartContext
	}
	return ""
}

func (x *CoreDocument) GetCustomDims() []*customdim.CustomDimension {
	if x != nil {
		return x.CustomDims
	}
	return nil
}

var File_indexing_core_proto protoreflect.FileDescriptor

var file_indexing_core_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65, 0x63, 0x74, 0x61,
	0x72, 0x61, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x69, 0x6e, 0x67, 0x1a, 0x10, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x5f, 0x64, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xad, 0x01,
	0x0a, 0x10, 0x43, 0x6f, 0x72, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61,
	0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6a, 0x73, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x46, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f,
	0x64, 0x69, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x76, 0x65, 0x63, 0x74, 0x61, 0x72, 0x61, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x69, 0x6e,
	0x67, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x69, 0x6d, 0x73, 0x22, 0x8c, 0x02,
	0x0a, 0x0c, 0x43, 0x6f, 0x72, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65, 0x63, 0x74, 0x61, 0x72,
	0x61, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x6f, 0x72, 0x65, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x05, 0x70, 0x61, 0x72,
	0x74, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x70, 0x61,
	0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x12, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x46, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x64,
	0x69, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x76, 0x65, 0x63, 0x74, 0x61, 0x72, 0x61, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x69, 0x6e, 0x67,
	0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x69, 0x6d, 0x73, 0x42, 0x51, 0x0a, 0x14,
	0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65, 0x63, 0x74, 0x61, 0x72, 0x61, 0x2e, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x69, 0x6e, 0x67, 0x42, 0x12, 0x43, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x69,
	0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x25, 0x76, 0x65, 0x63, 0x74, 0x61, 0x72,
	0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x69, 0x6e, 0x67, 0x63, 0x6f, 0x72, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_indexing_core_proto_rawDescOnce sync.Once
	file_indexing_core_proto_rawDescData = file_indexing_core_proto_rawDesc
)

func file_indexing_core_proto_rawDescGZIP() []byte {
	file_indexing_core_proto_rawDescOnce.Do(func() {
		file_indexing_core_proto_rawDescData = protoimpl.X.CompressGZIP(file_indexing_core_proto_rawDescData)
	})
	return file_indexing_core_proto_rawDescData
}

var file_indexing_core_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_indexing_core_proto_goTypes = []interface{}{
	(*CoreDocumentPart)(nil),          // 0: com.vectara.indexing.CoreDocumentPart
	(*CoreDocument)(nil),              // 1: com.vectara.indexing.CoreDocument
	(*customdim.CustomDimension)(nil), // 2: com.vectara.indexing.CustomDimension
}
var file_indexing_core_proto_depIdxs = []int32{
	2, // 0: com.vectara.indexing.CoreDocumentPart.custom_dims:type_name -> com.vectara.indexing.CustomDimension
	0, // 1: com.vectara.indexing.CoreDocument.parts:type_name -> com.vectara.indexing.CoreDocumentPart
	2, // 2: com.vectara.indexing.CoreDocument.custom_dims:type_name -> com.vectara.indexing.CustomDimension
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_indexing_core_proto_init() }
func file_indexing_core_proto_init() {
	if File_indexing_core_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_indexing_core_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoreDocumentPart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_indexing_core_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoreDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_indexing_core_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_indexing_core_proto_goTypes,
		DependencyIndexes: file_indexing_core_proto_depIdxs,
		MessageInfos:      file_indexing_core_proto_msgTypes,
	}.Build()
	File_indexing_core_proto = out.File
	file_indexing_core_proto_rawDesc = nil
	file_indexing_core_proto_goTypes = nil
	file_indexing_core_proto_depIdxs = nil
}
