// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.8.0
// source: admin_security.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	_ "vectara.com/public/proto/status"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomerRole int32

const (
	CustomerRole_CustomerRole_None CustomerRole = 0
	// The owner is the root user of the account. Only an owner can shut
	// down the account completely.
	CustomerRole_CustomerRole_Owner CustomerRole = 1
	// An account administrator can do things like create corpora, add or remove users etc.
	CustomerRole_CustomerRole_Admin CustomerRole = 2
	// View and modify billing-related information for the account.
	CustomerRole_CustomerRole_Billing_Admin CustomerRole = 3
	// View and modify corpus-related information for the account.
	CustomerRole_CustomerRole_Corpus_Admin CustomerRole = 4
)

// Enum value maps for CustomerRole.
var (
	CustomerRole_name = map[int32]string{
		0: "CustomerRole_None",
		1: "CustomerRole_Owner",
		2: "CustomerRole_Admin",
		3: "CustomerRole_Billing_Admin",
		4: "CustomerRole_Corpus_Admin",
	}
	CustomerRole_value = map[string]int32{
		"CustomerRole_None":          0,
		"CustomerRole_Owner":         1,
		"CustomerRole_Admin":         2,
		"CustomerRole_Billing_Admin": 3,
		"CustomerRole_Corpus_Admin":  4,
	}
)

func (x CustomerRole) Enum() *CustomerRole {
	p := new(CustomerRole)
	*p = x
	return p
}

func (x CustomerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_security_proto_enumTypes[0].Descriptor()
}

func (CustomerRole) Type() protoreflect.EnumType {
	return &file_admin_security_proto_enumTypes[0]
}

func (x CustomerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomerRole.Descriptor instead.
func (CustomerRole) EnumDescriptor() ([]byte, []int) {
	return file_admin_security_proto_rawDescGZIP(), []int{0}
}

var File_admin_security_proto protoreflect.FileDescriptor

var file_admin_security_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65, 0x63, 0x74,
	0x61, 0x72, 0x61, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x94, 0x01, 0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x5f,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x10, 0x02, 0x12,
	0x1e, 0x0a, 0x1a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x5f,
	0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x10, 0x03, 0x12,
	0x1d, 0x0a, 0x19, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x5f,
	0x43, 0x6f, 0x72, 0x70, 0x75, 0x73, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x10, 0x04, 0x42, 0x48,
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65, 0x63, 0x74, 0x61, 0x72, 0x61, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x42, 0x13, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x1e, 0x76, 0x65, 0x63, 0x74, 0x61, 0x72,
	0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_security_proto_rawDescOnce sync.Once
	file_admin_security_proto_rawDescData = file_admin_security_proto_rawDesc
)

func file_admin_security_proto_rawDescGZIP() []byte {
	file_admin_security_proto_rawDescOnce.Do(func() {
		file_admin_security_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_security_proto_rawDescData)
	})
	return file_admin_security_proto_rawDescData
}

var file_admin_security_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_security_proto_goTypes = []interface{}{
	(CustomerRole)(0), // 0: com.vectara.admin.CustomerRole
}
var file_admin_security_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_security_proto_init() }
func file_admin_security_proto_init() {
	if File_admin_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_security_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_security_proto_goTypes,
		DependencyIndexes: file_admin_security_proto_depIdxs,
		EnumInfos:         file_admin_security_proto_enumTypes,
	}.Build()
	File_admin_security_proto = out.File
	file_admin_security_proto_rawDesc = nil
	file_admin_security_proto_goTypes = nil
	file_admin_security_proto_depIdxs = nil
}
