# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.4

    - name: Go Mod
      run: go mod tidy

    - name: Install dependencies
      run: |
          go get .
          go get google.golang.org/protobuf
          go get google.golang.org/grpc/credentials

    - name: Build
      run: go build -o $GITHUB_WORKSPACE/myapp

    - name: list artifacts
      run: |
         ls $GITHUB_WORKSPACE -al
    - name: Copy artifacts
      run: |
        mkdir -p $HOME/deploy
        cp $GITHUB_WORKSPACE/myapp $HOME/deploy

    - name: Deploy to Oracle Cloud VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OC_VM_HOST }}
        username: opc
        key: ${{ secrets.OC_SSH_KEY }}
        script: |
          sudo systemctl stop vectara.service || true  # Stop the service if it's running, ignore errors
          cp $HOME/deploy/myapp /home/opc/apps
          sudo systemctl start vectara.service


