# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -o myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Copy artifacts
      run: |
        mkdir -p $HOME/deploy
        cp myapp $HOME/deploy/

    - name: Deploy to Oracle Cloud VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OC_VM_HOST }}
        username: opc
        key: ${{ secrets.OC_SSH_KEY }}
        script: |
          sudo systemctl stop vectara  # Stop your existing service if it's running
          cp $HOME/deploy/myapp /path/to/your/destination/
          sudo systemctl start vactara  # Start your service

